NUMBER_IN = 'Пожалуйста, введите количество шестиугольников, располагаемых в ряд: '
NUMBER_ERROR = 'Оно должно быть от 4 до 20: '
RED = 'красный'
BLUE = 'синий'
GREEN = 'зеленый'
YELLOW = 'желтый'
ORANGE = 'оранжевый'
PURPLE = 'пурпурный'
PINK = 'розовый'
REDCOLOR = 'red'
BLUECOLOR = 'blue'
GREENCOLOR = 'green'
YELLOWCOLOR = 'yellow'
ORANGECOLOR = 'orange'
PURPLECOLOR = 'purple'
PINKCOLOR = 'pink'

